### ISSUE TITLE
Why are the gifs so FAST?

### ISSUE THREAD

**Issue by shanewmurphy** [sureskumar/sketch-isometric#10]
Could you make the gifs any faster because I can't see exactly how to use your plugin? Honestly the most unhelp how to use example I've never seen.

**Comment by sureskumar** [comment]
Sorry that its not helpful. I will add slower GIFs, the trick is, slower GIFs have large file size and github does not let embed anything above 5MB. Meanwhile, please refer to the 'Features' section of the readme file. Cheers!
