### ISSUE TITLE
It always generates a gray shape?

### ISSUE THREAD

**Issue by splimola** [sureskumar/sketch-isometric#11]
No matter what type of artboard or rectangle shape I select, it only generates a gray isometric rectangle? Should it not at least adopt the colour of the original shape?

Your GIFs are way too fast to understand what steps I might be missing.

**Comment by pixime** [comment]
Same for me with an artboard and a simple rectangle as well. Sketch v49 (51002)

**Comment by keoshi** [comment]
Same here, even when starting from a simple colored rectangle.

> Sketch 49 (51002)

![isometric-sketch](https://user-images.githubusercontent.com/390760/37148186-6b0e6fa8-22c1-11e8-9744-a8027d763f20.gif)

**Comment by keoshi** [comment]
I just figured it out... The selling point of this plugin kind of becomes moot, but here it goes: Isometric doesn't actually translate your object or artboard to an isometric view, it just uses that size to generate an empty, grey placeholder.

To actually apply your artwork, you have to use Magic Mirror (or similar):

> Map Top Surface
> [Magic Mirror](https://magicsketch.io/mirror/) plugin can be used to map the desired artboard on top of the Isometric view. 

<img src="https://camo.githubusercontent.com/dd6dc0fe8a172b4228fc0e2cf5c1d69c142f6337/687474703a2f2f7777772e73757265736b756d61722e636f6d2f736b657463682d69736f6d65747269632f6769746875625f696d67732f736b657463685f69736f6d65747269635f64656d6f5f362e676966">

**Comment by pixime** [comment]
Thank you Filipe for your clear feedback.

**Comment by splimola** [comment]
> To actually apply your artwork, you have to use Magic Mirror (or similar):

Thanks for that. That does rather make this plugin rather ... less useful than it appeared in the Bohemian Coding newsletter ...  :|
