### ISSUE TITLE
Support for corner radius 

### ISSUE THREAD

**Issue by abinashmohanty** [sureskumar/sketch-isometric#14]
Hi @sureskumar first of all thanks a lot for making this plugin. I was just wondering is it possible to also maintain its border/radius that would make the isometric view awesome :)

**Comment by sureskumar** [comment]
Thats a popular feature request. I am trying to figure out a formula to solve this, but have had no luck until now. will surely make it happen soon. Cheers!

**Comment by abinashmohanty** [comment]
Thanks
