### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Raghav789** [sureskumar/sketch-isometric#16]
I did exactly As shown in the gif all it did was create a gray isometric box !!! and nothing in your screen capture .gif I can see magic mirror 3 option what is going on?

**Comment by jerrenhanley** [comment]
Same for me, what am I missing?

**Comment by sureskumar** [comment]
Hey Raghav,

Thanks for writing. Sorry the the delay in responding.

As mentioned in the instructions, you need to use Magic Mirror plugin (free version) to map the contents of your artboard to the generated isometric shape. Alternately you can also use Angle 2 plugin (free) to do this as well.

Hope this helps!

Cheers
Sures
