### ISSUE TITLE
Just get grey rectangle

### ISSUE THREAD

**Issue by FourTeeTwo** [sureskumar/sketch-isometric#17]
I've installed the plugin fine, I'm using Sketch v49.1 and when I select an artboard and click Plugins > Sketch Isometric > Generate Isometric View all I get is a grey rectangle.

I see the Rotate, Angle, Depth and Scale options, but the newly created isometric rectangle doesn't have the selected artboard on it.

**Comment by FourTeeTwo** [comment]
Oh hang on, I wasn't using Magic Mirror to map the surface. I was under the impression your plugin did both things. Issue sorted.

**Comment by FourTeeTwo** [comment]
Is there any other way to map an artboard onto the surface of the new rectangle, other than Magic Mirror?

**Comment by sureskumar** [comment]
Hey sorry about the mess! :) You can also use Angle 2 plugin.
