### ISSUE TITLE
Top Front Side Views

### ISSUE THREAD

**Issue by jayliu50** [sureskumar/sketch-isometric#20]
Congrats on another awesome plugin!

Feature Request: It would be phenomenal if this plugin could support the top front and side views, then one could really do isometric illustration: https://design.tutsplus.com/tutorials/how-to-create-advanced-isometric-illustrations-using-the-ssr-method--vector-1058

**Comment by sureskumar** [comment]
Great idea! will try my best in the coming weeks. Cheers!
