### ISSUE TITLE
Using symbols, groups

### ISSUE THREAD

**Issue by DoktorVonMixer** [sureskumar/sketch-isometric#22]
Hi. First of all : excellent plugin !
Now, for my workflow, question :
- can't make it work with groups
- can't make it work with symbols
- can't make it work with artboards
Both display only an isometric rectangle with nothing in it except the "depth walls". I guess the plugin is just not updated for the latest sketch version ?

Is there something i am missing ?
Flattenning the layer to one bmp doesn't work either.
i'm sure i'm missing something…

**Comment by DoktorVonMixer** [comment]
Oh. I see in the gifs that you are using magic mirror. Will try that. If MM is required, maybe a hint in your plugin description saying it is required / recommended would be a plus ! 👍

**Comment by DoktorVonMixer** [comment]
(I should really spend time working a plugin out before posting crappy comments… sorry).

Tested with Magic Mirror latest release, works like a charm. A lot of new options are available for magicmirror, and it's really awesome. (you should defenitely mention MagicMirror on your description page, it's a perfect combination !)

One "bug" / improvement i can see : you draw 3 rectangles when you generate the isometric group, but there is a gap between the 3 rectangles (due to the way sketch handles antialiasing). It would be really really neat to have a 4rth rectangle that takes up the whole space, like an addition of the 3 paths, just to cover the seams. That, or the bottom right thickness rectangle to take the whole space (but that would give less control).

Otherwise… defenitely recommended, and using it in my workflow. It really rocks. Thanks so much for your contribution ! <3

**Comment by sureskumar** [comment]
Hey, thanks for the wonderful tip. I am sorry that I could not respond on time. Cheers!
