### ISSUE TITLE
Plug-In not working on 50.2

### ISSUE THREAD

**Issue by Guito1986** [sureskumar/sketch-isometric#29]
It was just to let you know that the plug-in doesn't work on Sketch 50.2 no stress

**Comment by sureskumar** [comment]
The updated version is working with Sketch 50.2.

**Comment by andresv2** [comment]
Plug-in isn't working for Sketch 51.3. 
Do you have something coming up soon. Or do you know of other resources to turn a board to an isometric view?
Thanks
