### ISSUE TITLE
Doesn't copy

### ISSUE THREAD

**Issue by Aanriek** [sureskumar/sketch-isometric#3]
Trying out the plugin, all that every happens when I follow the steps is I get a blank isometric shape. Whatever is on the artboard or rectangle I'm trying to transfer into an isometric shape doesn't show up

**Comment by sureskumar** [comment]
Hi Aanriek, As mentioned in the instructions, you need to use 'Magic Mirror' plugin to map the contents from the artboard to the generated isometric shape. Hope this helps. Cheers!
