### ISSUE TITLE
Its not working in sketch 49.3, Mac OSX

### ISSUE THREAD

**Issue by jonptr** [sureskumar/sketch-isometric#33]
I tried running the plugin. The popup comes with 4 options but after I select "Done", nothing happens. Can someone help me.

**Comment by cleocadio** [comment]
I can Confirm This, nothing happens

**Comment by cleocadio** [comment]
In my case I have Sketch 50.2

**Comment by randallmlough** [comment]
I was experiencing the same thing (it was working before 50.2). I fixed it by deleting the plugin from the package manager I was using (Sketchpacks), and manually removed it from Sketch's plugin folder, and then manually reinstalled using the plugin file from this repo. That seemed to fix it. So if you're using a package manager that might be the cause of these issues.

**Comment by sureskumar** [comment]
Hey guys, sorry for the inconvenience. I had to update bunch of stuff in this plugin to make it work in Sketch 50.2. If you are using an earlier sketch version, please download the plugin from here https://github.com/sureskumar/sketch-isometric/archive/6b565185808b1003d34e1dab46799cf93d72de29.zip

If you are using Sketch 50.2 and still does not work, has Randal mentions, try downloading from here  https://github.com/sureskumar/sketch-isometric/archive/74e3a948291bdc0532b2883ea5bbdd919eaa4844.zip

**Comment by loracy** [comment]
@sureskumar it works with Sketch 50.2!! Thanks for making this awesome plugin!!!

**Comment by sureskumar** [comment]
Thanks for confirming! :)
