### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kashifkiduniya** [sureskumar/sketch-isometric#35]
Isometric is not working with my Sketch 4.6.2.
Is there any version compatibility?

**Comment by sureskumar** [comment]
Hey, sorry for the inconvenience. I had to update bunch of stuff in this plugin to make it work in Sketch 50.2. If you are using an earlier sketch version, please download the plugin from here https://github.com/sureskumar/sketch-isometric/archive/6b565185808b1003d34e1dab46799cf93d72de29.zip
