### ISSUE TITLE
Ensure all requests are made using https

### ISSUE THREAD

**Issue by hamishmcneill** [sureskumar/sketch-isometric#36]
An `http:` request is attempted when Sketch Isometric is installed, however App Transport Security (ATS) blocks the request.

I've noted that a number of other urls in the manifest.json for this plugin also use `http:` only. [We recommend](https://developer.sketchapp.com/blog/2016-09-26-plugin-latest-v40#nsapptransportsecurity) changing over to use `https:` for all such requests.

**Steps to Reproduce**

1. Install Sketch Isometric, 2.1.0
2. Launch Sketch (current version 51.1)

**Expected Result**

- No http requests are attempted
- All previous `http:` links are updated to `https:` 

**Actual Result**

```
Could not read image data at /Users/<User>/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch-Isometric.sketchplugin/Contents/Resources/http:/www.sureskumar.com/sketch-isometric/github_imgs/logo.png «Plugin Developer»

App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
```

**Comment by sureskumar** [comment]
Done, thanks for pointing out!
