### ISSUE TITLE
How can you edit an existing isometric conversion?

### ISSUE THREAD

**Issue by khash** [sureskumar/sketch-isometric#37]
This is a very helpful plugin but I can't figure out how to change the attributes of an existing isometric shape generated. For example once converted an artboard with Depth = 20, I would like to be able to change that to 10 without having to regenerate the whole thing again. It seems it's not possible as all actions will generate a fresh new isometric shape group.

It seems this is possible but I can't see it in the animated gifs as they run very fast.

**Comment by sureskumar** [comment]
Thanks for the feedback Khash. This feature is not supported in the current version. I will add in the next version. Cheers!
