### ISSUE TITLE
Not working with Sketch 51.2

### ISSUE THREAD

**Issue by arthurkrupa** [sureskumar/sketch-isometric#38]
I have v3.0.0 installed. After running the plugin, the popup appears but nothing happens after pressing "Done".

Environment: Sketch 51.2 + macOS 10.13.6

**Comment by sureskumar** [comment]
Thanks for bringing this up.
I have the same Mac and Sketch version, but not able to recreate the error :(

**Comment by Manevolence** [comment]
I on the other hand still am on 48.2, is there no support for earlier versions?

**Comment by sureskumar** [comment]
If you are using an earlier sketch version, please download the plugin from here https://github.com/sureskumar/sketch-isometric/archive/6b565185808b1003d34e1dab46799cf93d72de29.zip but this does not have the latest features :(

**Comment by sureskumar** [comment]
Please update Sketch to latest version 52 and download the latest plugin from here: https://github.com/sureskumar/sketch-isometric/releases/download/v4.0/Sketch-Isometric.sketchplugin.zip and try again. Cheers!
