### ISSUE TITLE
Generated image is empty

### ISSUE THREAD

**Issue by futuandrei** [sureskumar/sketch-isometric#39]
Hi, as I generate the image I get it light grey empty. Have you experienced this problem before, I wonder if this is general problem with plugins I have or this is plugin-specific. 

My sketch version is 51.2 and Isometric Plugin's version is 3.0.0.

I have a problem with other plugin at the moment too, it's "Chart" with the version of 3.6.0, there I can't make the menu visible.

Thanks in advance,
Br, Andrei

**Comment by sureskumar** [comment]
Hey Andrei,

Thanks for writing. Sorry the the delay in responding.

As mentioned in the instructions, you need to use Magic Mirror plugin (free version) or Angle 2 plugin (free version) to map the contents of your artboard to the generated isometric shape.

Hope this helps!

Cheers
Sures
