### ISSUE TITLE
Sketch 52

### ISSUE THREAD

**Issue by Preen** [sureskumar/sketch-isometric#41]
Cant seem to get isometric to work with Sketch 52, nothing happens when I try to create a block. The dialog opens but then nothing is generated.

**Comment by sureskumar** [comment]
Thanks for reporting. Its fixed now. Please download the latest plugin from here: https://github.com/sureskumar/sketch-isometric/releases/download/v4.0/Sketch-Isometric.sketchplugin.zip

**Comment by Preen** [comment]
Great. Thanks for a really fast fix!
