### ISSUE TITLE
No isometric view after run the plugin

### ISSUE THREAD

**Issue by Jojr** [sureskumar/sketch-isometric#43]
I selected the artboard and clicked Generate isometric view, but the isometric view does not appear in the Sketch after clicked in done.

Is my mistake?

I'm use Magic Mirror v3 and Sketch 51.3.

![captura de tela 2018-10-15 as 17 37 31](https://user-images.githubusercontent.com/8437807/46976889-0e1e9f00-d0a1-11e8-90b0-6e05a4373845.png)

**Comment by andiechu** [comment]
Same problem here.My Sketch version is 49.1.

**Comment by Jojr** [comment]
I've updated to Sketch 52.2 and solved it.
Tanks @andiechu
