### ISSUE TITLE
Sketch Isometric no longer working?

### ISSUE THREAD

**Issue by Adedamolisher** [sureskumar/sketch-isometric#44]
Hi there, 

I've been using your plugin and it's been working amazingly. However it suddenly seems to have stopped working? 

I've used the plugin before in conjunction with the angle & magic mirror but seem to still be having the issue. I've also deactivated a whole host of my plugins to see if one could potentially be causing for the plugin to no longer work. 

Sadly, this did not fix the problem. Please feel free to see the screenshots below. 

Mac OS: MacOS Sierra 10.12.6 
Sketch Version: 51.3

Thanks, 

Ade 

<img width="378" alt="screen shot 2018-10-19 at 14 46 01" src="https://user-images.githubusercontent.com/28831141/47222059-c7d18480-d3ad-11e8-8149-072e32746888.png">
<img width="552" alt="screen shot 2018-10-19 at 14 46 13" src="https://user-images.githubusercontent.com/28831141/47222060-c86a1b00-d3ad-11e8-9d23-af30ad14a13b.png">
<img width="480" alt="screen shot 2018-10-19 at 14 46 20" src="https://user-images.githubusercontent.com/28831141/47222061-c86a1b00-d3ad-11e8-82fc-edd06c00502d.png">

**Comment by sureskumar** [comment]
Hey Ade, Sorry for the inconvenience. Updating to the latest Sketch version should fix the problem. Cheers!
