### ISSUE TITLE
it's no work!

### ISSUE THREAD

**Issue by Mecil9** [sureskumar/sketch-isometric#48]
I chose the picture and ran the plug-in. I could only see the rectangle. No picture was generated.

**Comment by oravecz** [comment]
Same; selected rectangle and ran plugin; no results.
Sketch v 51.2

**Comment by alexkaessner** [comment]
As written in the README:

> […]
>
> 4. Use Magic Mirror (free version) or Angle Plugin (free) to map the contents of your artboard to the generated isometric shape.
> ### This plugin DOES NOT
> - Map artboard contents to the generated isometric shapes. See step 4 above for details.
>
> […]

**Comment by sureskumar** [comment]
Thanks for answering Alexander.
