### ISSUE TITLE
input problem for depth value

### ISSUE THREAD

**Issue by alexkaessner** [sureskumar/sketch-isometric#49]
When deleting the number of the `Depth` value the isometric shapes disappear and the plug-in stops working. The other values accept a `null` value.

![screen recording](https://user-images.githubusercontent.com/6615076/50090408-bae3dc80-0208-11e9-9931-b7a75582b86e.gif)

_I'm using v4.0.0 with Sketch 52.5 on macOS 10.13.6_

**Comment by sureskumar** [comment]
Hey, have fixed this bug in the latest version. Please give it a try: https://github.com/sureskumar/sketch-isometric/releases/download/v4.1/Sketch-Isometric.sketchplugin.zip Cheers!
