### ISSUE TITLE
Sketchpacks

### ISSUE THREAD

**Issue by mikeprecious** [sureskumar/sketch-isometric#5]
Hi there, I can't seem to locate the plugin via Sketch Packs app.

**Comment by barmallion** [comment]
In Sketch Runner too...

**Comment by sureskumar** [comment]
Sorry about this guys, Both Runner and SketchPacks take sometime to catalogue new plugins. It already appears here (https://github.com/sureskumar/plugin-directory) but not yet here (https://sketchapp.com/extensions/plugins/). So I guess, meanwhile you guys can download the plugin from my git or wait for 1 or 2 days for sketch folks to update their listing. Thanks for the support. Cheers!
