### ISSUE TITLE
Sketch 52.6

### ISSUE THREAD

**Issue by josephjpearce** [sureskumar/sketch-isometric#50]
Doesn't seem to be working in Sketch 52.6, when I hit "Generate Isometric View" dialog appears but no preview of the isometric artboard or rectangle comes up.

**Comment by reimertz** [comment]
Same issue for me. Anything I can do to help here @sureskumar?

**Comment by reimertz** [comment]
@josephjpearce I got it to work by updating from 2.0.1 to 4.1.0. I thought I had the latest version but when I updated the plugin using Sketchpacks, it worked.

Hope this helps.
