### ISSUE TITLE
Isometric view don't work

### ISSUE THREAD

**Issue by ramonfalabella** [sureskumar/sketch-isometric#57]
When i select a image or square and gererate a isometric view nothing happen.

Sketch Version: 53.3
Isometric View Version: 2.1.0

**Comment by sureskumar** [comment]
Hey, sorry to hear that. Does it generate a gray box?

**Comment by bfan1256** [comment]
Hey @sureskumar , I still don't see anything interestingly. This is what I see. I'm pretty sure I have the most updated version from Sketch Plugins:

<img width="708" alt="Screen Shot 2019-04-12 at 10 06 22 AM" src="https://user-images.githubusercontent.com/15917894/56043132-a4f3ad80-5d0a-11e9-81e6-eb14231df163.png">


You have a mockup like such:

<img width="1679" alt="1" src="https://user-images.githubusercontent.com/15917894/56043014-5a723100-5d0a-11e9-87f9-351068231332.png">

Then I attempt to create an isometric view:

<img width="1676" alt="Screen Shot 2019-04-12 at 10 05 03 AM" src="https://user-images.githubusercontent.com/15917894/56043058-7bd31d00-5d0a-11e9-83fc-373821f83c06.png">


But nothing shows up:
<img width="1676" alt="Screen Shot 2019-04-12 at 10 05 11 AM" src="https://user-images.githubusercontent.com/15917894/56043076-855c8500-5d0a-11e9-889d-6b8c68dc682f.png">
