### ISSUE TITLE
sketch 54 

### ISSUE THREAD

**Issue by GabrielVecchio** [sureskumar/sketch-isometric#59]
apparently it aint working on sketch 54.1 :/ 

I can write all the specs I want to generate the isometric view but it simply doesnt finish. I click on 'done' and then... nothing.

**Comment by sureskumar** [comment]
Hi, sorry that its not working. Can you try installing the latest version of the plugin from here: https://github.com/sureskumar/sketch-isometric/releases/download/v4.2/Sketch-Isometric.sketchplugin.zip
