### ISSUE TITLE
Generating artboard without any content

### ISSUE THREAD

**Issue by MC-TLAB** [sureskumar/sketch-isometric#6]
Everytime when I generate an isometric artboard there is no content on it, although I selected the full artboard.

**Comment by barmallion** [comment]
Use Magic Mirror 3 plugin

**Comment by MC-TLAB** [comment]
I wanted to use the "Sketch Isometric Plugin", because it is FREE. That was the main reason. I already heard about Magic Mirror, but I don't want to purchase it.

**Comment by barmallion** [comment]
I understand. But isomeric make only shape transformation. If you want transform artboard content - you must use Magic Mirror. See demo video on isometric plugin main page.

**Comment by MC-TLAB** [comment]
Oh, for real? Didn't know that. Thanks for the clarification ^^
