### ISSUE TITLE
Layer not showing in the isometric object.

### ISSUE THREAD

**Issue by acreea2** [sureskumar/sketch-isometric#62]
The option to create the isometric object shows up like normal but when I hit the CTA it just creates a blank gray isometric layer.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/3720566/63819159-e1b2f080-c909-11e9-9691-0a28d8a9cfb8.png">

**Comment by jayliu50** [comment]
same here

**Comment by sureskumar** [comment]
Hey,

Thanks for writing. Sorry the the delay in responding.

As mentioned in the instructions, you need to use Magic Mirror plugin (free version) or Angle 2 plugin (free version) to map the contents of your artboard to the generated isometric shape.

Hope this helps!

Cheers
Sures
