### ISSUE TITLE
Feature request - respect rounded corners or shape

### ISSUE THREAD

**Issue by spyderdsn** [sureskumar/sketch-isometric#64]
Issue: rounded corners are not preserved, it will be nice to have something similar to the example below:

**Current issue:**
<img width="1030" alt="Screen Shot 2019-12-16 at 6 07 27 pm" src="https://user-images.githubusercontent.com/7193691/70886225-140a6a00-202f-11ea-9890-0bd3bd05630e.png">

**Example:**
![1_SoRtkIqajcFq4inwVLS5UA](https://user-images.githubusercontent.com/7193691/70886287-41571800-202f-11ea-9176-1359490e354c.png)

**Comment by sureskumar** [comment]
Hi, this has been a popular feature request. Unfortunately, I dont know how to achieve this. Any help will be appreciated. Cheers!
