### ISSUE TITLE
Isometrify other Objects

### ISSUE THREAD

**Issue by jansemka** [sureskumar/sketch-isometric#7]
Would be cool to isometrify other objects for example icons.

**Comment by sureskumar** [comment]
Ya, but not sure how to do that at this point... :(

**Comment by jansemka** [comment]
It should be easy i think? These are just scaling, rotation and stretching calculations. What about grouping icons together with a square and do the magic on the group? Just speaking out ideas loudly :-)

**Comment by sureskumar** [comment]
Unfortunately I am not doing the scaling, rotating and stretching as I have yet figured how to stretch programmatically in sketch.  Currently I am using a formula to map the four points from 2D to Isometric geometry.
