### ISSUE TITLE
No webview present

### ISSUE THREAD

**Issue by jschelling** [sureskumar/sketch-isometric#8]
Plugin creates a blank isometric artboard

Get this in the plugin output.log

```
No WebView present. Event cannot be posted to the web UI.
 «Plugin Output»
No WebView present. Event cannot be posted to the web UI.
 «Plugin Output»

```

**Comment by sebastienb** [comment]
I'm also getting a blank isometric artboard

**Comment by sureskumar** [comment]
Hey Guys,

Thanks for writing.

As mentioned in the instructions and demo GIFs, you need to use Magic Mirror plugin (free version) to map the contents of your artboard to the generated isometric shape.

Hope this helps!

Cheers
Sures
